/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellerOnboardingRouteImport } from './routes/seller-onboarding'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceMyListingsRouteImport } from './routes/marketplace/my-listings'

const SellerOnboardingRoute = SellerOnboardingRouteImport.update({
  id: '/seller-onboarding',
  path: '/seller-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceMyListingsRoute = MarketplaceMyListingsRouteImport.update({
  id: '/marketplace/my-listings',
  path: '/marketplace/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/seller-onboarding': typeof SellerOnboardingRoute
  '/marketplace/my-listings': typeof MarketplaceMyListingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/seller-onboarding': typeof SellerOnboardingRoute
  '/marketplace/my-listings': typeof MarketplaceMyListingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/seller-onboarding': typeof SellerOnboardingRoute
  '/marketplace/my-listings': typeof MarketplaceMyListingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/seller-onboarding' | '/marketplace/my-listings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/seller-onboarding' | '/marketplace/my-listings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/seller-onboarding'
    | '/marketplace/my-listings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  SellerOnboardingRoute: typeof SellerOnboardingRoute
  MarketplaceMyListingsRoute: typeof MarketplaceMyListingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seller-onboarding': {
      id: '/seller-onboarding'
      path: '/seller-onboarding'
      fullPath: '/seller-onboarding'
      preLoaderRoute: typeof SellerOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/my-listings': {
      id: '/marketplace/my-listings'
      path: '/marketplace/my-listings'
      fullPath: '/marketplace/my-listings'
      preLoaderRoute: typeof MarketplaceMyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  SellerOnboardingRoute: SellerOnboardingRoute,
  MarketplaceMyListingsRoute: MarketplaceMyListingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
